details:
    page_title: Mendez
layout:
    - row_1_of_3:
        - col_2_of_4:
            - tile_template: weather
              tile_id: weather
              title: Weather
              classes:

        - col_1_of_4:
            - tile_template: empty
              tile_id: empty
              title: Empty Tile
              classes:

        - col_1_of_4:
            - tile_template: empty
              tile_id: empty
              title: Calendar
              classes:
    
    - row_1_of_3:
        - col_1_of_4:
            - tile_template: empty
              tile_id: empty
              title: empty
              classes:
              
        - col_1_of_4:
            - tile_template: empty
              tile_id: empty
              title: empty
              classes:

        - col_1_of_4:
            - tile_template: empty
              tile_id: empty
              title: Empty Tile
              classes:

        - col_1_of_4:
            - tile_template: empty
              tile_id: empty
              title: Calendar
              classes:
    
    
    - row_1_of_3:
        - col_1_of_4:
            - tile_template: line_chart
              tile_id: power_daily
              title: Power by Day
              timeout: 86400
              classes:

        - col_1_of_4:
            - tile_template: line_chart
              tile_id: power_hourly
              title: Power by Hour
              timeout: 86400
              classes:

        - col_1_of_4:
            - tile_template: big_value
              tile_id: power_electricity
              title: Electricity
              timeout: 86400
              classes:

        - col_1_of_4:
            - tile_template: big_value
              tile_id: power_gas
              title: Gas
              timeout: 86400
              classes:
